typography_spectrum: 0.47373
color:
  brandColors:
    - '#fdfdfd'
    - '#d0d0d0'
    - '#a5a5a5'
    - '#6c6c6c'
    - '#454545'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99935
analytics:
  google: null
  facebook: null
  twitter: null
name: vanstralen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: vanstralen
description: random things
purpose: []
