name: vanstralen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46525
title: vanstralen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d0d0d0'
    - '#a5a5a5'
    - '#6c6c6c'
    - '#454545'
  brandStrength: 0.8621224339585751
  lightness: 0.7963941877242178
  saturation: 0.6148966231849045
  rhythmicContrast: 0.9868324096314609
purpose: []
