name: vanstralen
favicon: null
layout_spectrum: 0.00254
typography_spectrum: 0.47373
title: vanstralen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d0d0d0'
    - '#a5a5a5'
    - '#6c6c6c'
    - '#454545'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
